version: "3.6"
services:
  nginx:
    build: docker/nginx
    container_name: nginx_gmg_front
    ports:
      - "81:81"
    volumes:
      - ./docker/data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - python

  python:
    build: docker/python
    container_name: python_gmg_front
    working_dir: /code
    restart: always
    volumes:
      - .:/code

networks:
  default: 
    external:
      name: shared-gmg
